pipeline {
  agent {
    kubernetes {
      yaml '''
        apiVersion: v1
        kind: Pod
        spec:
          containers:
          - name: maven
            image: maven:alpine
            command:
            - cat
            tty: true
          - name: node
            image: node:16-alpine3.12
            command:
            - cat
            tty: true
          - name: dotnetcore
            image: mcr.microsoft.com/dotnet/runtime:7.0
            command:
            - cat
            tty: true
          - name: cosign
            image: yogendra123raju/cosign:t1
            command:
            - cat
            tty: true
        '''
    }
  }
  stages {
    stage('Run maven') {
      steps {
        container('maven') {
          sh 'mvn -version'
          sh ' echo Enter Into maven Container > hello.txt'
          sh ' cat hello.txt'
          sh 'ls -last'
        }
        container('node') {
          sh 'npm version'
          sh ' echo Enter Into node Container >> hello.txt'
          sh 'cat hello.txt'
          sh 'ls -last'
          sh 'wget "https://github.com/sigstore/cosign/releases/download/v1.6.0/cosign-linux-amd64"'
          sh 'mv cosign-linux-amd64 /usr/local/bin/cosign'
          sh 'chmod +x /usr/local/bin/cosign'
        }
        container('dotnetcore') {
          sh 'dotnet --info'
          sh ' echo Enter Into dotnetcore Container >> hello.txt'
          sh 'cat hello.txt'
          sh 'ls -last'
        }
        container('cosign') {
          sh 'ls -last'
          sh '/usr/local/bin/cosign login hub.docker.io -u yogendra123raju -p Raju@123'
          sh '/usr/local/bin/cosign sign --key /usr/local/bin/cosign.key yogendra123raju/cosign:t1'
        }
      }
    }
  }
}