pipeline {
  agent {
    kubernetes {
      yaml '''
        apiVersion: v1
        kind: Pod
        spec:
          containers:
          - name: maven
            image: maven:alpine
            command:
            - cat
            tty: true
          - name: node
            image: node:16-alpine3.12
            command:
            - cat
            tty: true
          - name: dotnetcore
            image: mcr.microsoft.com/dotnet/runtime:7.0
            command:
            - cat
            tty: true
        '''
    }
  }
  stages {
    stage('Run maven') {
      steps {
        container('maven') {
          sh 'mvn -version'
          sh ' echo Enter Into maven Container > hello.txt'
          sh ' cat hello.txt'
          sh 'ls -last'
        }
        container('node') {
          sh 'npm version'
          sh ' echo Enter Into node Container >> hello.txt'
          sh 'cat hello.txt'
          sh 'ls -last'
        }
        container('dotnetcore') {
          sh 'dotnet --info'
          sh ' echo Enter Into dotnetcore Container >> hello.txt'
          sh 'cat hello.txt'
          sh 'ls -last'
        }
      }
    }
  }
}