apiVersion: v1
kind: Pod
metadata:
  name: jenkins-master-slave
spec:
  containers:
  - name: jenkins-master-slave
  #  image: yogendra123raju/jenkins:Feb16-2023
    image: jenkins/jenkins:lts
    ports:
    - containerPort: 8080
    - containerPort: 50000
    volumeMounts:
      - name: jenkins-home
        mountPath: /var/jenkins_home
    resources:
      limits:
        memory: "1512Mi"
        cpu: "1500m"
  - name: jenkins-slave
    image: jenkins/jnlp-slave
    command:
    - cat
    tty: true
    resources:
      limits:
        memory: "2512Mi"
        cpu: "2500m"
  restartPolicy: Never
  volumes:
        - name: jenkins-home
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: LoadBalancer
  selector:
    app: jenkins-master-slave
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
status:
  loadBalancer:
    ingress:
      - ip: 20.219.227.52

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp
spec:
  type: ClusterIP
  ports:
    - port: 50000
      targetPort: 50000
  selector:
    app: jenkins-master-slave